### ISSUE TITLE
Accessibility Problems

### ISSUE THREAD

**Issue by Mcgurk-Adam** [ShineSolar/EmailSignature#8]
This one doesn't match the usual bug report format:

When you run lighthouse, it throws accessibility errors (indiscernible text) on the orange color for the h1 and the button for the mobile landing page. We need to fix those errors!

**Comment by Mcgurk-Adam** [comment]
Try changing the color to the site blue

**Comment by Saitama2016** [comment]
I changed the color to site blue based on the brand blue options in the scss file. [Here is a pull request I made](https://github.com/ShineSolar/EmailSignature/pull/9)

**Comment by Mcgurk-Adam** [comment]
On Pull Request #9, this problem was fixed
